name: pyrate01
channels:
- nmoraitakis
- ioos
dependencies:
- cython
- flask
- pyhdf
- gdal
- grib_api
- hdf4
- hdf5
- ipython
- matplotlib
- networkx
- numpy
- pygrib
- pyproj
- scipy
- nose
- pillow
- pip:
  - luigi==1.3.0
  - parmap
  - glob2
  - git+https://github.com/daleroberts/pypar