name: pyrate
channels:
  - nmoraitakis
  - mutirri
dependencies:
  - python=2.7
  - numpy=1.9.0
  - scipy=0.16.0
  - Cython=0.22.1
  - nose=1.3.7
  - networkx=1.9.1
  - matplotlib=1.4.3
  - Flask=0.10.1
  - Pillow=2.8.2
  - GDAL=1.11.2
  - pyproj=1.9.4
  - pygrib=2.0.0
  - pyhdf=0.8.3
  - pip:
    - luigi==1.3.0
    - parmap==1.2.3
